# Skip the Ubuntu/Debian system-wide compinit in /etc/zsh/zshrc.
#
# This is the official opt-out documented at the bottom of /etc/zsh/zshrc:
#   if (( ${${(@f)"$(</etc/os-release)"}[(I)ID*=*ubuntu]} )) && [[ -z "$skip_global_compinit" ]]; then
#       autoload -U compinit; compinit
#   fi
#
# We already run compinit ourselves in plugins.zsh, AFTER zinit has loaded the
# plugins and set up fpath. If the global compinit also runs (first, with the
# default fpath), the completion dump gets built/validated twice and is
# invalidated by the fpath change, forcing a full ~3.4s dump rebuild on every
# interactive startup. Skipping it keeps startup fast (~0.5s) while keeping a
# single, stable completion dump generated by plugins.zsh.
skip_global_compinit=1
