general.import = [
"~/.config/alacritty/themes/themes/vscode.toml",
]

[window]
blur = true
padding = {x=10,y=3}
dynamic_title = false
opacity = 0.7

[font]
normal = {family = "JetBrainsMono Nerd Font", style = "Regular"}
size = 12

[env]
TERM = "xterm-256color"
TERMINFO = "/usr/share/terminfo"

[cursor]
style = {shape="Block", blinking="Always"}
