general.import = [
	"~/.config/alacritty/themes/themes/afterglow.toml",
	"~/.config/alacritty/keys.toml"
]

[window]
decorations = "buttonless"
blur = true
opacity = 0.75
title = "alacritty"
dynamic_title = false
startup_mode = "Maximized"
option_as_alt = "Both"

[scrolling]
history = 50000
multiplier = 3

[font]
size = 14

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Heavy"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Heavy Italic"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Medium Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[env]
TERM = "xterm-256color"

[cursor]
style = {shape="Beam", blinking="on"}
