general.import = [
	"~/.config/alacritty/themes/themes/catppuccin_mocha.toml",
	"~/.config/alacritty/keys.toml",
	"~/.config/alacritty/window.toml"
]

[mouse]
hide_when_typing = true

[scrolling]
history = 50000
multiplier = 3

[font]
size = 13
normal = { family = "Maple Mono NF CN", style = "Regular" }
bold = { family = "Maple Mono NF CN", style = "Bold" }
italic = { family = "Maple Mono NF CN", style = "Italic" }
bold_italic = { family = "Maple Mono NF CN", style = "Bold Italic" }

[cursor]
style = {shape="Beam", blinking="on"}

[terminal]
osc52 = "OnlyCopy"

[env]
TERM = "xterm-256color"
