[keyboard]
bindings = [
  { key = "H", mods = "Alt", chars = "\u0001\u0068" },  # Ctrl+a then h
  { key = "J", mods = "Alt", chars = "\u0001\u006a" },  # Ctrl+a then j
  { key = "K", mods = "Alt", chars = "\u0001\u006b" },  # Ctrl+a then k
  { key = "L", mods = "Alt", chars = "\u0001\u006c" },  # Ctrl+a then l
]
